Carp 25 store wr swaps
vacuumlabs/wtp pull request #22
Opened 2022-10-25 09:53 UTC by MichalVido

#25

2022-10-25 10:35 UTC, miksax requested changes
some nitpicks

2022-10-25 10:35 UTC, miksax commented on src/sink.rs
> +                            let swaps = wr_get_swaps(transaction_record, &db).await.unwrap();
unnecessery unwrap

2022-10-25 10:35 UTC, miksax commented on src/sink.rs
> +                                for swap in swaps.iter() {
`swap in swaps.iter().flatten()` is better

2022-10-25 10:35 UTC, miksax commented on src/entity/swap.rs
> +    pub timestamp: DateTime,
we decided to store tx_id instead of timestamp

2022-10-25 10:35 UTC, miksax commented on src/queries.rs
> +        .filter(
Is it possible to insert it without the previous select?
The selection will be part of the insert query like (https://dba.stackexchange.com/questions/2973/how-to-insert-values-into-a-table-from-a-select-query-in-postgresql)

2022-10-25 10:41 UTC, MichalVido commented on src/entity/swap.rs
> +    pub timestamp: DateTime,
tx_id is already there. Should I just delete timestamp column?

2022-10-26 09:56 UTC, MichalVido commented on src/server.rs
> +async fn get_swap_history(
same name as queries::get_swap_history. come up with better name?

2022-10-26 09:58 UTC, MichalVido commented on src/queries.rs
> +        .filter(
didn't resolve this one. create another issue?

2022-10-26 11:26 UTC, miksax requested changes
Almost OK,
some nitpicks are present

2022-10-26 11:26 UTC, miksax commented on src/server.rs
> +    Ok(serde_json::to_string(&data)?)
is it possible to to map true/false from direction to enum "buy/sell"?

2022-10-26 11:26 UTC, miksax commented on src/queries.rs
> +    let token1_model = token::Entity::find()
token1_id and token2 id are present in request, so it is not necessary to show it in result

2022-10-26 12:33 UTC, MichalVido commented on src/queries.rs
> +    let token1_model = token::Entity::find()
your comment is pointing at a line that stores token_id to the database. did you mean to comment queries::get_swap_history instead of queries::insert_swap?

2022-10-26 12:47 UTC, miksax approved these changes
LGTM

2022-10-26 12:51 UTC, merged